<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headTitle() ?>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="en-US" />
        <link href="<?php echo $this->baseUrl('/css/style.css') ?>"
              media="screen"rel="stylesheet" type="text/css" />
        <script type="text/javascript">
            var baseUrl = "<?= $this->baseUrl()?>";
        </script>

        <?= $this->headScript() ?>
    </head>
    <body>
        <center>
            <div id="content">
                <?php echo $this->layout()->content ?>
            </div>

            <div id="footer">
                <p><img alt="Powered by Zend Framework" src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
                <p><img alt="Powered by Doctrine" src="http://dev.juokaz.com/wp-content/uploads/2009/11/doctrine-orm-php5.png" /></p>

            </div>
        </center>

    </body>
</html>