<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headTitle() ?>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="en-US" />
        <meta name="keywords" content="word1, word2" />
        <link href="<?php echo $this->baseUrl('css/style.css') ?>"
              media="screen"rel="stylesheet" type="text/css" />
    </head>
    <body>
        <center>
            <div id="content">
                <?php echo $this->layout()->content ?>
            </div>

            <div id="footer">
                <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
            </div>
        </center>

    </body>
</html>