
<h1>Desenvolvendo Applicaćões Web com Zend Framework e Doctrine PHP</h1>

<h3>
    <a href="http://wiki.softwarelivre-vs.org/#head-1002a215df3c5eaaa2a894599b11b39df89668df" >
        FLISOL 2010 - Festival Latino-Americano de Instalação de Software Livre
    </a>
</h3>

<div id="conteudo-site">
    <ul>
        <li>
            <a href="<?php echo $this->baseUrl('/cadastro')?>">Demostraćão Cadastro:</a>
        </li>
    </ul>

</div>

<div id="more-information">
    Referências:
    <ul>
        <li>
            Zend Framework
            <ul>
                <li>
                    <a href="http://framework.zend.com/">Zend Framework Website</a>
                </li>
                <li>
                    <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
                </li>
                <li>
                    <a href="http://www.zfbrasil.com/forum/">Fórum Zend Brasil</a>
                </li>
                <li>
                    <a href="http://www.zendcasts.com">Zend Casts</a>
                </li>
                <li>
                    #zftalk (irc.freenode.org)
                </li>
            </ul>
        </li>
        <li>
            Doctrine
            <ul>
                <li>
                    <a href="http://www.doctrine-project.org/">Doctrine Website</a>
                </li>
                <li>
                    <a href="http://www.doctrine-project.org/documentation">Online Documentation</a>
                </li>
                <li>
                    <a href="http://www.zendcasts.com/tag/doctrine">Zend Casts</a>
                </li>
                <li>
                    #doctrine (irc.freenode.org)
                </li>
            </ul>
        </li>
    </ul>
</div>
