
<div id="more-information">
    <h2> Referências:     </h2>

    <div id="zend">
            <h3>Zend Framework</h3>
            <ul>
                <li>
                    <a href="http://framework.zend.com/">Zend Framework Website</a>
                </li>
                <li>
                    <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
                </li>
                <li>
                    <a href="http://www.zfbrasil.com/forum/">Fórum Zend Brasil</a>
                </li>
                <li>
                    <a href="http://www.zendcasts.com">Zend Casts</a>
                </li>
                <li>
                    #zftalk (irc.freenode.org)
                </li>
            </ul>
        </div>

    
     <div id="doctrine">
            <h3>Doctrine</h3>
            <ul>
                <li>
                    <a href="http://www.doctrine-project.org/">Doctrine Website</a>
                </li>
                <li>
                    <a href="http://www.doctrine-project.org/documentation">Online Documentation</a>
                </li>
                <li>
                    <a href="http://www.zendcasts.com/tag/doctrine">Zend Casts</a>
                </li>
                <li>
                    #doctrine (irc.freenode.org)
                </li>
            </ul>
    </div>
</div>
