<?php

/**
 * City
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class City extends Base_City
{

    /**
     * Busca cidades pelo ID do Estado
     * @param int $stateID
     * @return Doctrine_Collection
     */
    public static function getCitiesByState($stateID)
    {
        return Doctrine_Query::create()
            ->from('City')
            ->where('City.state_id = ?', $stateID)
            ->orderBy('name')
            ->execute();
    }

    /**
     * Busca json no formato {"id":"name","id":"name"}
     * @param id $stateID id do estado
     * @return string o Json para popular o select via ajax
     */
    public function getSelectArrayByState($stateID)
    {
        $cities = self::getCitiesByState($stateID);
        $array = array();
        foreach($cities as $city) {
                $array[$city->id] = $city->name;
        }
        return $array;
    }
}