<?php

/**
 * State
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class State extends Base_State
{

    /**
     * Busca todos os estados em ordem alfabetica de nome
     * @return  Doctrine_Collection
     */
    public function getAll()
    {
        $dql = new Doctrine_Query();
        $dql->from('State')->orderBy('name');
        return $dql->execute();
    }

    /**
     * Este array serve para popular o Zend_Form_Element_Select
     * @return array
     */
    public static function getSelectArray()
    {
        $states = array();
        foreach(self::getAll() as $state){
            $states[$state->id] = $state->name;
        }
        return $states;
    }
    
}